## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'smaract'  #for instance daqmx
package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_smaract' #to modify
description = 'Set of PyMoDAQ plugins for linear actuators from Smaract (SLC positioners). MCS and MCS2 controllers are supported.'

author = 'David Bresteau'
author-email = 'david.bresteau@cea.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['instrumental-lib', 'pymodaq>=4.0.7']

[features]  # defines the plugin features contained into this plugin
instruments = true  # true if plugin contains instrument classes (else false, notice the lowercase for toml files)
extensions = false  # true if plugins contains dashboard extensions
models = false  # true if plugins contains pid models
h5exporters = false  # true if plugin contains custom h5 file exporters
scanners = false  # true if plugin contains custom scan layout (daq_scan extensions)

